rootProject.name = "VoiceCloneApp"
include ':app'
dependencyResolutionManagement {
  repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
  repositories {
    google()
    mavenCentral()
    // optional: sometimes third-party artifacts are on jitpack
    maven { url "https://jitpack.io" }
  }
}
