rootProject.name = "Voice-Clone"

dependencyResolutionManagement {
    // Make the project use the repositories declared here (not project/module repositories)
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        // Required for AndroidX/Compose artifacts
        google()
        // Required for many libraries
        mavenCentral()
        // Optional, keep if you use libraries from JitPack
        maven { url 'https://jitpack.io' }
    }
}

include ':app'
