rootProject.name = "Voice-Clone"

dependencyResolutionManagement {
    // Ensure project uses the repositories declared here, not per-project repositories
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()
        // optional if you use artifacts from jitpack
        maven { url 'https://jitpack.io' }
    }
}

include ':app'
